name: soateco
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: 0.19.0
  provider: ^6.1.4
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.3
  http: ^1.2.0
  crypto: ^3.0.3
  webview_flutter: ^4.7.0
  pay: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gpay_config.json
    - lib/assets/icons/
